import type { Scholarship } from "@/lib/types";

export const scholarships: Scholarship[] = [
  {
    id: "fulbright-us",
    name: "Fulbright Foreign Student Program",
    country: "USA",
    flag: "🇺🇸",
    organization: "U.S. Department of State",
    degree: ["masters", "phd"],
    funding: "full",
    fields: ["Any", "Public Policy", "STEM", "Social Sciences"],
    deadline: "2025-10-07",
    description:
      "Fulbright supports graduate study and research in the United States for international students through country-specific Fulbright commissions and U.S. embassies. It is one of the most recognized fully funded pathways for future academic, public-sector, and community leaders.",
    requirements: {
      gpa: "Strong academic record expected; many country programs look for roughly 3.0/4.0 or equivalent",
      ielts: "Varies by host university and local Fulbright commission",
      toefl: "Often required later for university placement if English proficiency is not otherwise documented",
      essays: [
        "Study or research objectives",
        "Personal statement",
        "Leadership or community impact examples",
      ],
      other: [
        "Eligibility and deadlines vary by home-country Fulbright commission or U.S. embassy",
        "References and academic transcripts are commonly required",
      ],
    },
    link: "https://foreign.fulbrightonline.org/",
  },
  {
    id: "chevening-uk",
    name: "Chevening Scholarship",
    country: "UK",
    flag: "🇬🇧",
    organization: "UK Foreign, Commonwealth & Development Office",
    degree: ["masters"],
    funding: "full",
    fields: ["Any", "Public Policy", "Business", "Development"],
    deadline: "2025-10-07",
    description:
      "Chevening funds one-year master's degrees in the UK for emerging leaders with strong professional and leadership potential. The award covers tuition, living costs, and travel for scholars selected through a competitive global process.",
    requirements: {
      gpa: "No fixed GPA threshold, but strong academic standing is expected",
      ielts: "No Chevening-wide English test requirement after policy updates; universities may still require it",
      essays: [
        "Leadership and influence",
        "Networking",
        "Study in the UK",
        "Career plan",
      ],
      other: [
        "At least two years of work experience is typically required",
        "Applicants apply to eligible UK master's courses separately",
      ],
    },
    link: "https://www.chevening.org/scholarships/",
  },
  {
    id: "daad-germany",
    name: "DAAD EPOS Scholarship",
    country: "Germany",
    flag: "🇩🇪",
    organization: "DAAD",
    degree: ["masters", "phd"],
    funding: "full",
    fields: ["Development", "Engineering", "Economics", "Public Policy"],
    deadline: "2025-10-31",
    description:
      "DAAD's EPOS scholarships support postgraduate courses in Germany that are tied to sustainable development and professional advancement. Funding usually includes a monthly stipend, insurance, and travel support depending on the program.",
    requirements: {
      gpa: "Good to very good degree results expected",
      ielts: "Program-specific; many English-language courses expect around 6.0 to 6.5",
      toefl: "Program-specific alternative to IELTS where accepted",
      essays: [
        "Motivation for development-related postgraduate study",
        "Professional goals and relevance to home country",
      ],
      other: [
        "Relevant professional experience is often required for EPOS programs",
        "Deadlines vary by specific DAAD-listed course",
      ],
    },
    link: "https://www.daad.de/en/studying-in-germany/scholarships/daad-scholarships/",
  },
  {
    id: "gates-cambridge-uk",
    name: "Gates Cambridge Scholarship",
    country: "UK",
    flag: "🇬🇧",
    organization: "Gates Cambridge Trust",
    degree: ["masters", "phd"],
    funding: "full",
    fields: ["Any", "STEM", "Social Sciences", "Humanities"],
    deadline: "2025-12-03",
    description:
      "Gates Cambridge funds outstanding international applicants for full-time postgraduate study at the University of Cambridge. The scholarship is designed for academically exceptional candidates with leadership potential and a commitment to improving others' lives.",
    requirements: {
      gpa: "Exceptional academic record expected",
      ielts: "Must meet Cambridge course language requirements",
      toefl: "Accepted where Cambridge course allows TOEFL",
      essays: [
        "Gates Cambridge statement",
        "Research proposal or course-specific statement where applicable",
      ],
      other: [
        "Applicants must apply for admission to Cambridge and the scholarship together",
        "Academic references are required",
      ],
    },
    link: "https://www.gatescambridge.org/apply/",
  },
  {
    id: "erasmus-mundus-europe",
    name: "Erasmus Mundus Joint Masters Scholarship",
    country: "Europe",
    flag: "🇪🇺",
    organization: "European Commission",
    degree: ["masters"],
    funding: "full",
    fields: ["Any", "STEM", "Climate", "Data", "Policy"],
    deadline: "2026-01-15",
    description:
      "Erasmus Mundus scholarships fund joint master's degrees delivered by university consortia across multiple European countries. Awardees usually receive tuition coverage, travel support, and a living allowance while rotating across partner campuses.",
    requirements: {
      gpa: "Competitive academic record required by each consortium",
      ielts: "Usually around 6.5 or equivalent, but set by each program",
      toefl: "Accepted by many consortia as an IELTS alternative",
      essays: ["Motivation statement", "Program fit and future goals"],
      other: [
        "Requirements and deadlines vary by specific Erasmus Mundus program",
        "Transcripts and recommendation letters are commonly required",
      ],
    },
    link: "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters-scholarships",
  },
  {
    id: "mext-japan",
    name: "MEXT Monbukagakusho Scholarship",
    country: "Japan",
    flag: "🇯🇵",
    organization: "Ministry of Education, Culture, Sports, Science and Technology",
    degree: ["undergraduate", "masters", "phd"],
    funding: "full",
    fields: ["Any", "STEM", "Social Sciences", "Humanities"],
    deadline: "2025-05-31",
    description:
      "MEXT offers fully funded Japanese government scholarships through embassy and university recommendation tracks. It supports undergraduate and graduate study and often includes tuition, stipend, and airfare.",
    requirements: {
      gpa: "Strong academic standing expected by embassy or university track",
      ielts: "Not always mandatory; proof of English or Japanese ability may be requested",
      toefl: "Accepted when institutions request English proof",
      essays: [
        "Field of study and research plan",
        "Reasons for choosing Japan and the program",
      ],
      other: [
        "Exact deadlines vary by Japanese embassy and recommendation route",
        "Medical and document legalization requirements are common",
      ],
    },
    link: "https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/",
  },
  {
    id: "australia-awards",
    name: "Australia Awards Scholarship",
    country: "Australia",
    flag: "🇦🇺",
    organization: "Australian Government",
    degree: ["undergraduate", "masters", "phd"],
    funding: "full",
    fields: ["Development", "Public Policy", "Education", "STEM"],
    deadline: "2025-04-30",
    description:
      "Australia Awards funds study for students from eligible developing countries, including many in Southeast Asia, at participating Australian institutions. The scholarship is built around leadership development and long-term contribution to home-country progress.",
    requirements: {
      gpa: "Varies by country profile and chosen institution",
      ielts: "Applicants generally need to meet the English requirement of their proposed institution",
      toefl: "Accepted if the institution allows it",
      essays: [
        "Development impact and leadership goals",
        "Study rationale and planned contribution after return",
      ],
      other: [
        "Eligibility is country-specific and may include work experience",
        "Most intakes open in February and close around the end of April",
      ],
    },
    link: "https://www.australiaawardsglobal.alumni.gov.au/scholarships",
  },
  {
    id: "adb-japan",
    name: "ADB-Japan Scholarship Program",
    country: "Japan",
    flag: "🇯🇵",
    organization: "Asian Development Bank",
    degree: ["masters"],
    funding: "full",
    fields: ["Economics", "Management", "Science", "Technology"],
    deadline: "2026-01-15",
    description:
      "The ADB-Japan Scholarship Program supports postgraduate study in economics, management, science, and technology at designated institutions in Asia and the Pacific. It targets applicants with strong academic merit and a clear development-oriented career path.",
    requirements: {
      gpa: "Strong undergraduate record expected",
      ielts: "Institution-specific English requirement",
      toefl: "Institution-specific alternative where accepted",
      essays: ["Study objectives and development impact", "Career plans after graduation"],
      other: [
        "Applicants apply through participating institutions, each with its own deadline",
        "At least two years of full-time professional experience is commonly expected",
      ],
    },
    link: "https://www.adb.org/work-with-us/careers/japan-scholarship-program",
  },
  {
    id: "vlir-uos-belgium",
    name: "VLIR-UOS Scholarship",
    country: "Belgium",
    flag: "🇧🇪",
    organization: "VLIR-UOS",
    degree: ["masters"],
    funding: "full",
    fields: ["Agriculture", "Environment", "Public Health", "Development"],
    deadline: "2026-02-01",
    description:
      "VLIR-UOS funds selected master's and training programs in Belgium for applicants from eligible countries, including several in Southeast Asia. The scholarship emphasizes practical impact, academic promise, and development relevance.",
    requirements: {
      gpa: "Solid academic record required by the chosen program",
      ielts: "Program-specific English requirements apply",
      toefl: "Accepted by some host institutions",
      essays: [
        "Motivation and program fit",
        "Development relevance for home community or sector",
      ],
      other: [
        "Applicants must choose a VLIR-UOS funded program",
        "Some programs require professional experience",
      ],
    },
    link: "https://www.vliruos.be/en/scholarships/6",
  },
  {
    id: "schwarzman-scholars-china",
    name: "Schwarzman Scholars",
    country: "China",
    flag: "🇨🇳",
    organization: "Tsinghua University",
    degree: ["masters"],
    funding: "full",
    fields: ["Leadership", "Public Policy", "Economics", "Global Affairs"],
    deadline: "2025-09-10",
    description:
      "Schwarzman Scholars is a one-year, fully funded master's program in global affairs at Tsinghua University in Beijing. It looks for future leaders with strong academics, leadership records, and the ability to thrive in an intensive cohort model.",
    requirements: {
      gpa: "Highly competitive academic performance expected",
      ielts: "Usually 7.0 IELTS or equivalent if prior degree was not in English",
      toefl: "Typically 100 internet-based TOEFL or equivalent if required",
      essays: ["Leadership essay", "Statement of purpose"],
      other: [
        "Global applicants typically apply between April and September",
        "Video introduction and recommendations are required",
      ],
    },
    link: "https://www.schwarzmanscholars.org/admissions/",
  },
  {
    id: "gks-korea",
    name: "Global Korea Scholarship",
    country: "South Korea",
    flag: "🇰🇷",
    organization: "National Institute for International Education",
    degree: ["undergraduate", "masters", "phd"],
    funding: "full",
    fields: ["Any", "STEM", "Business", "Humanities"],
    deadline: "2025-09-30",
    description:
      "The Global Korea Scholarship funds undergraduate and graduate study in South Korea through embassy and university tracks. It usually covers tuition, stipend, settlement support, language training, and airfare for selected scholars.",
    requirements: {
      gpa: "Applicants typically need to rank within the top 20% or meet the official minimum conversion threshold",
      ielts: "Not universally required, but language readiness strengthens the application",
      toefl: "Accepted where universities ask for English scores",
      essays: ["Personal statement", "Study plan"],
      other: [
        "Deadlines vary by embassy and university track, even within the same cycle",
        "Recommendation letters and health statement are required",
      ],
    },
    link: "https://www.studyinkorea.go.kr/",
  },
  {
    id: "new-zealand-asean-scholars",
    name: "Manaaki New Zealand ASEAN Scholars Award",
    country: "New Zealand",
    flag: "🇳🇿",
    organization: "New Zealand Government",
    degree: ["undergraduate", "masters", "phd"],
    funding: "full",
    fields: ["Climate", "Agriculture", "Governance", "Economic Development"],
    deadline: "2025-02-28",
    description:
      "Manaaki New Zealand Scholarships support tertiary study for candidates from eligible countries whose goals align with New Zealand's development priorities. Funding generally includes tuition, living support, travel, and establishment costs.",
    requirements: {
      gpa: "Academic competitiveness depends on program and country demand",
      ielts: "Applicants must meet English language requirements for admission",
      toefl: "Accepted if recognized by the host institution",
      essays: ["Development impact", "Study plan and commitment to return"],
      other: [
        "Eligibility includes country and sector priorities",
        "Application windows are often limited and can close in late February",
      ],
    },
    link: "https://www.nzscholarships.govt.nz/",
  },
  {
    id: "humphrey-fellowship-us",
    name: "Hubert H. Humphrey Fellowship",
    country: "USA",
    flag: "🇺🇸",
    organization: "U.S. Department of State",
    degree: ["masters"],
    funding: "full",
    fields: ["Public Policy", "Education", "Journalism", "Public Health"],
    deadline: "2025-07-31",
    description:
      "The Humphrey Fellowship is a non-degree professional enrichment program in the United States for mid-career leaders. It combines academic study, professional collaboration, and leadership development rather than a standard graduate degree pathway.",
    requirements: {
      gpa: "No universal GPA cutoff, but a strong prior academic record helps",
      ielts: "English proficiency is expected; exact testing rules vary by nominating country",
      toefl: "May be requested depending on placement needs",
      essays: [
        "Professional goals and leadership record",
        "Contribution to public service or sector impact",
      ],
      other: [
        "Designed for professionals with substantial full-time experience",
        "Applicants are nominated through local binational commissions or U.S. embassies",
      ],
    },
    link: "https://www.humphreyfellowship.org/",
  },
  {
    id: "ares-belgium",
    name: "ARES Scholarship",
    country: "Belgium",
    flag: "🇧🇪",
    organization: "ARES",
    degree: ["masters"],
    funding: "full",
    fields: ["Public Health", "Development", "Human Rights", "Agriculture"],
    deadline: "2025-10-18",
    description:
      "ARES funds one-year specialized master's programs and continuing education training in Belgium for applicants from selected partner countries. The program focuses on candidates who can use their studies to create impact after returning home.",
    requirements: {
      gpa: "Strong academic background expected",
      ielts: "Language requirements depend on the chosen program",
      toefl: "Accepted where institutions permit it",
      essays: [
        "Motivation for the program",
        "Professional relevance and impact after return",
      ],
      other: [
        "Eligibility includes a maximum age guideline and partner-country list",
        "Application windows often open in mid-year and close in the autumn",
      ],
    },
    link: "https://www.ares-ac.be/en/cooperation-au-developpement/scholarships",
  },
  {
    id: "swiss-government-excellence",
    name: "Swiss Government Excellence Scholarship",
    country: "Switzerland",
    flag: "🇨🇭",
    organization: "Swiss Confederation",
    degree: ["masters", "phd"],
    funding: "full",
    fields: ["Research", "Arts", "STEM", "Humanities"],
    deadline: "2025-11-15",
    description:
      "The Swiss Government Excellence Scholarships support postgraduate research, doctoral work, postdoctoral study, and selected arts awards through the Federal Commission for Scholarships for Foreign Students. Country-specific embassy channels publish each cycle's application package and timing.",
    requirements: {
      gpa: "Excellent academic achievement expected",
      ielts: "Depends on host institution or research language expectations",
      toefl: "May be accepted where relevant",
      essays: ["Research proposal or study plan", "Motivation statement"],
      other: [
        "Applicants usually need a host professor invitation for research awards",
        "Deadlines vary by country and embassy package",
      ],
    },
    link: "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
  },
];

export const scholarshipsById = new Map(
  scholarships.map((scholarship) => [scholarship.id, scholarship]),
);
